export const mockEquipment = [
    {
    id: 1,
    serialNumber: 'PUMP-1001',
    model: 'InfusePro X2',
    chargeLevel: 85.00,
    status: 'Available',
    facilityId: 1,
    },
    {
    id: 2,
    serialNumber: 'PUMP-1002',
    model: 'InfusePro X2',
    chargeLevel: 15.50,
    status: 'In-Use',
    facilityId: 1,
    },
    {
    id: 3,
    serialNumber: 'VENT-2001',
    model: 'AirFlow V5',
    chargeLevel: 72.00,
    status: 'In-Use',
    facilityId: 2,
    },
    {
    id: 4,
    serialNumber: 'VENT-2002',
    model: 'AirFlow V5',
    chargeLevel: 10.00,
    status: 'Maintenance',
    facilityId: 2,
    },
    {
    id: 5,
    serialNumber: 'MON-3001',
    model: 'VitalWatch M3',
    chargeLevel: 95.00,
    status: 'Available',
    facilityId: 3,
    },
    {
    id: 6,
    serialNumber: 'MON-3002',
    model: 'VitalWatch M3',
    chargeLevel: 18.25,
    status: 'In-Use',
    facilityId: 3,
    },
    {
    id: 7,
    serialNumber: 'IMG-4001',
    model: 'MobileScan C1',
    chargeLevel: 45.00,
    status: 'Maintenance',
    facilityId: 4,
    },
    {
    id: 8,
    serialNumber: 'PUMP-1003',
    model: 'InfusePro X2',
    chargeLevel: 5.00,
    status: 'Offline',
    facilityId: 4,
    },
    {
    id: 9,
    serialNumber: 'MED-TEST-001',
    model: 'Infusion Pump',
    chargeLevel: 75.00,
    status: 'Available',
    facilityId: 1,
    },
];